import 'package:personal_expense/models/transaction.dart';

final List<Transaction> transactionSamples = [
  Transaction(
    id: 't1',
    title: 'New Shoes',
    amount: 1.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't2',
    title: 'New Car',
    amount: 2.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't3',
    title: 'New Shoes',
    amount: 1.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't4',
    title: 'New Car',
    amount: 2.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't5',
    title: 'New Shoes',
    amount: 1.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't6',
    title: 'New Car',
    amount: 2.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't7',
    title: 'New Shoes',
    amount: 1.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't8',
    title: 'New Car',
    amount: 2.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't9',
    title: 'New Shoes',
    amount: 1.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't10',
    title: 'New Car',
    amount: 2.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't11',
    title: 'New Shoes',
    amount: 1.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't12',
    title: 'New Car',
    amount: 2.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't13',
    title: 'New Shoes',
    amount: 1.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't14',
    title: 'New Car',
    amount: 2.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't15',
    title: 'New Shoes',
    amount: 1.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't16',
    title: 'New Car',
    amount: 2.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't17',
    title: 'New Shoes',
    amount: 1.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't18',
    title: 'New Car',
    amount: 2.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't19',
    title: 'New Shoes',
    amount: 1.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't20',
    title: 'New Car',
    amount: 2.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't21',
    title: 'New Shoes',
    amount: 1.99,
    date: DateTime.now(),
  ),
  Transaction(
    id: 't22',
    title: 'New Car',
    amount: 2.99,
    date: DateTime.now(),
  ),
];
